{% set name = "pipx" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pipx-{{ version }}.tar.gz
  sha256: 840610e00103e3d49ae24b6b51804b60988851a5dd65468adb71e5a97e2699b2

build:
  noarch: python
  number: 0

  entry_points:
    - pipx = pipx.main:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - hatch-vcs >=0.4
    - hatchling >=1.18
    - pip
  run:
    - python >=3.8
    - argcomplete >=1.9.4
    - colorama >=0.4.4
    - packaging >=20
    - platformdirs >=2.1
    - tomli
    - userpath !=1.9,>=1.6

test:
  imports:
    - pipx
    - pipx.commands
  commands:
    - pip check
    - pipx --help
  requires:
    - pip

about:
  home: https://github.com/pypa/pipx
  summary: Install and Run Python Applications in Isolated Environments
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maresb
