{% set name = "pipx" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pipx-{{ version }}.tar.gz
  sha256: db07ec2a3a15d772a71b2608c134f065d7fbc51d4654abe6adfc412800ed6ba4

build:
  noarch: python
  number: 0

  entry_points:
    - pipx = pipx.main:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - hatchling >=0.15
    - pip
  run:
    - python >=3.8
    - argcomplete >=1.9.4
    - colorama >=0.4.4
    - packaging >=20
    - platformdirs >=2.1
    - tomli
    - userpath !=1.9.0,>=1.6

test:
  imports:
    - pipx
    - pipx.commands
  commands:
    - pip check
    - pipx --help
  requires:
    - pip

about:
  home: https://github.com/pypa/pipx
  summary: Install and Run Python Applications in Isolated Environments
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maresb
