{% set name = "pipx" %}
{% set version = "1.2.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pipx-{{ version }}.tar.gz
  sha256: 698777c05a97cca81df4dc6a71d9ca4ece2184c6f91dc7a0e4802ac51d86d32a

build:
  noarch: python
  number: 0

  entry_points:
    - pipx = pipx.main:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - hatchling >=0.15.0
  run:
    # https://github.com/pypa/pipx/blob/{{ version }}/pyproject.toml
    - python >=3.7
    - argcomplete >=1.9.4
    - colorama >=0.4.4
    - importlib-metadata >=3.3.0
    - packaging >=20.0
    - platformdirs >=2.1.0
    - userpath >=1.6.0,!=1.9.0
test:
  imports:
    - pipx
    - pipx.commands
  commands:
    - pip check
    - pipx --help
  requires:
    - pip

about:
  home: https://github.com/pypa/pipx
  summary: Install and Run Python Applications in Isolated Environments
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maresb
