{% set name = "pipx" %}
{% set version = "1.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pipx-{{ version }}.tar.gz
  sha256: d1908041d24d525cafebeb177efb686133d719499cb55c54f596c95add579286

build:
  noarch: python
  number: 0

  entry_points:
    - pipx = pipx.main:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - hatchling >=0.15.0
  run:
    # https://github.com/pypa/pipx/blob/{{ version }}/pyproject.toml
    - python >=3.7
    - argcomplete >=1.9.4
    - colorama >=0.4.4
    - importlib-metadata >=3.3.0
    - packaging >=20.0
    - userpath >=1.6.0

test:
  imports:
    - pipx
    - pipx.commands
  commands:
    - pip check
    - pipx --help
  requires:
    - pip

about:
  home: https://github.com/pypa/pipx
  summary: Install and Run Python Applications in Isolated Environments
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maresb
